launcher:
  _target_: stopes.core.Launcher
  log_folder: executor_logs
  cluster: local
  partition: null
  cache:
    _target_: stopes.core.FileCache
    caching_dir: /tmp/stopes_cache
  max_jobarray_jobs: 1000

defaults:
  - testing: eng_test.yaml
  - _self_
  
corpora:  ???
